apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efk-cloud
data:
  fluent.conf: |-
    @include kubernetes.conf
    #@include file.conf
    #Just an example of what kind of variables can come inside. This part does not apply as config. Do your config with ENV vars
    <match **>
      @type elasticsearch
      @id out_es
      @log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'https'}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      index_name efk-cloud-02
      type_name fluentd
    </match>
  kubernetes.conf: |-
    <match fluent.**>
      @type null
    </match>
    <source>
      @type tail
      @id in_tail_containers_logs
      path /var/log/customlog/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      format json
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>
